name: CraftCord
version: '${project.version}'
main: wolfdev1.com.github.craftcord.CraftCord
api-version: 1.18
authors: [ wolfdev1 ]
description: An spigot plugin for connect Discord and Minecraft Chat
